### ISSUE TITLE
Unknown error: json: cannot unmarshal object into Go struct field APIError.detail of type string

### ISSUE THREAD

**Issue by mmazurkevich** [replicate/replicate-go#38]
I've got it from `replicate-go@v0.14.2/apierror.go` `unmarshalAPIError` function. Exception at unmarshalling doesn't allow me to see the original root cause of the request failure.

Example of JSON:
```
{"detail":{"name":"Enter a valid name. This value may contain only lowercase letters, numbers, dashes, underscores, or periods, and may not start or end with a dash, underscore, or period."}}
```
failed with with the following exception:
`Unknown error: json: cannot unmarshal object into Go struct field APIError.detail of type string`

**Comment by mmazurkevich** [comment]
As I see in the example of error message from server there has to be no nested objects in the JSON from the server
https://replicate.com/docs/reference/http#rate-limits

**Comment by mattt** [comment]
Hi @mmazurkevich. Thanks for reporting. The response sent by Replicate's API for invalid models in the `POST /models` endpoint is incorrect. This is something we'll need to fix on our side.

**Comment by mattt** [comment]
@mmazurkevich I'm happy to report that this is now fixed. Replicate's API now returns error objects in the form of [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457.html) problem details. I just ran `replicate model create` with an invalid hardware sku, and it correctly repoted the error instead of panicking with that JSON error. Thanks again for reporting!
